module.exports = (app) => {
    const notes = require('../controllers/note.controller.js');
    const fs = require('fs');
    const multer = require('multer');
    const upload = multer({dest: '../../assets/uploads/'}); //setting the default folder for multer

    // Create a new Note
    app.post('/notes', notes.create);

    // Retrieve all Notes
    app.get('/notes', notes.findAll);

    // Retrieve a single Note with noteId
    app.get('/notes/:noteId', notes.findOne);

    // Update a Note with noteId
    app.put('/notes/:noteId', notes.update);

    // Delete a Note with noteId
    app.delete('/notes/:noteId', notes.delete);

//other imports and code will go here
    app.post('/upload', upload.single('fileData'), (req, res, next) => {
        console.log("image saving...")
        logger.info(req.file);//this will be automatically set by multer
        logger.info(req.body);
        //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
        fs.readFile(req.file.path, (err, contents) => {
            if (err) {
                console.log('Error: ', err);
            } else {
                console.log('File contents ', contents);
            }
        });
    });
}